# AWS Configuration
aws.region=us-east-1
aws.s3.bucket=njit-cs-643
aws.sqs.queue.url=https://sqs.us-east-1.amazonaws.com/079478445145/car-image-index-queue

# Car Detection Configuration
car.detection.min.confidence=90.0
car.detection.max.labels=10
car.detection.min.label.confidence=75.0
car.detection.max.images=10

# Text Recognition Configuration
text.recognition.output.path=src/main/output.txt
text.recognition.temp.dir=/tmp

# SQS Configuration
sqs.max.messages=1
sqs.wait.time.seconds=10

# Termination Signal
termination.signal=-1

